# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: xenial

os:
  - linux
  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_PKG=true  # Use the latest version from the default package manager
    - LAZ_VER=1.4.4 # Use specific (binary) release
    - LAZ_VER=1.8.2

matrix:
  include:
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm"
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./.travis.install.py

script:
  - lazbuild $LAZ_OPT my_lazarus_tests.lpi               # Build my_lazarus_test project
  - $LAZ_ENV ./bin/my_lazarus_tests --all --format=plain # Run my_lazarus_test testsuite

notifications:
  email:
    on_success: false
    on_failure: change
deploy:
  provider: releases
  file: bin/my_lazarus_tests
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: "EsKyIv31ZIMuUulVw90N+P4Ljap3XuXc1nMbjIMEycy2Zmf6J70by2HjTFjUIoEZi646r4/DBnQUH5i/CrOWcZV2pjDFCK3Dx6AQ3np+qzpaq59Z9OoWS1DV5cd9znW0m0mVXC3gSUttO+tcQXiIMepdrjCs4yKsVuxSIgIZTidq5WOYaOkeq0voS+FNb+0UJb3rHAf3FFLBifpgI/3/qBHCaBSwP/FDZbZaK1oB8Ew7sGnslJSpppMKIkldxtngwrlGGaXlMHkFG9AO5R4weA2IqgkEmh+gASktgrKMSuPhOiDY3FkBGhp3pknXV+3aGrQnEj2x+lcov0JQSQ3NJ68sr3cEuqsVHi7YAFyI8CbnvQhmQd2AiqclztZ5i0JUKYL8oA/EkQpsnFIKwfRhTVd+6dypZNgDi4WhjPEkJYVru86C7VHJ5T9yzLeG7ZyG09Zjy3k1Q5lvjXCkWD7g1s3Uq5VGZUARh4RrOnMgxqdhK5JXUh2yPxkcX6bmrNOHY2XkIm/BYNk1GiSbcAad3BE6zp/u87/PFQcXimpv92Y0nsMq66CNMz0fmUYqBVdWYpAWc1WF/UDRzWr19KHgZaYyENALGUAI2dJw9dZkSSwLQDRQK8CFbhsdcEIGEQTpUCRh1Tpm7lKsGh/xyCVIJ5jqVxl7UBE+ldDmWro9MzU="
